// Mid figure art (v2 D54): pure pixel grids in slot letters, no colours. Standing 5x10 px (5x5 cells),
// seated 8x10 px (8x5 cells). Derived once from the GPT sprite sheet (halved: eyes, hair, tie, legs and
// shoes kept) and re-lettered by hand; sprites.ts maps each slot to a colour.
//   H hair, S skin, T shirt, U shirt shade, K tie, P pants, F shoes, E eye, M mouth,
//   D desk top, B desk body, N monitor frame, C screen, . floor
import type { Facing } from './sprites'

export type Slot = 'H' | 'S' | 'T' | 'U' | 'K' | 'P' | 'F' | 'E' | 'M' | 'D' | 'B' | 'N' | 'C' | '.'
export const SLOTS: readonly string[] = ['H', 'S', 'T', 'U', 'K', 'P', 'F', 'E', 'M', 'D', 'B', 'N', 'C', '.']
export type Grid = readonly string[]

export const MID_STAND_W = 5
export const MID_STAND_H = 10
export const MID_SEAT_W = 8
export const MID_SEAT_H = 10

// Standing, idle: one grid per facing.
export const MID_IDLE: Readonly<Record<Facing, Grid>> = {
  down: [
    '.HHH.',
    'HHHHH',
    'HHHHH',
    'HESEH',
    'SSMSS',
    'TTSTT',
    'UTKTU',
    'SPPPS',
    '.P.P.',
    '.F.F.',
  ],
  up: [
    '.HHH.',
    'HHHHH',
    'HHHHH',
    'HHHHH',
    'SHHHS',
    'TTTTT',
    'UTTTU',
    'SPPPS',
    '.P.P.',
    '.F.F.',
  ],
  left: [
    '.HHH.',
    'HHHHH',
    'HSHHH',
    'SESHH',
    '.SSH.',
    '.TTT.',
    '.TTU.',
    '.PSS.',
    '..PP.',
    '.FFF.',
  ],
  right: [
    '.HHH.',
    'HHHHH',
    'HHHSH',
    'HHSES',
    '.HSS.',
    '.TTT.',
    '.UTT.',
    '.SSP.',
    '.PP..',
    '.FFF.',
  ],
}

// Standing, walking: four frames per facing. Down and up swing a leg out on frames 0 and 2 and pass through
// the idle legs on 1 and 3 with the hands swapped; left is the mirror of right.
export const MID_WALK: Readonly<Record<Facing, readonly Grid[]>> = {
  down: [
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HESEH',
        'SSMSS',
        'TTSTT',
        'UTKTU',
        'SPPPS',
        'PP.P.',
        'FF.F.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HESEH',
        'SSMSS',
        'TTSTT',
        'UTKTU',
        '.PPPS',
        '.P.P.',
        '.F.F.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HESEH',
        'SSMSS',
        'TTSTT',
        'UTKTU',
        'SPPPS',
        '.P.PP',
        '.F.FF',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HESEH',
        'SSMSS',
        'TTSTT',
        'UTKTU',
        'SPPP.',
        '.P.P.',
        '.F.F.',
      ],
  ],
  up: [
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HHHHH',
        'SHHHS',
        'TTTTT',
        'UTTTU',
        'SPPPS',
        'PP.P.',
        'FF.F.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HHHHH',
        'SHHHS',
        'TTTTT',
        'UTTTU',
        '.PPPS',
        '.P.P.',
        '.F.F.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HHHHH',
        'SHHHS',
        'TTTTT',
        'UTTTU',
        'SPPPS',
        '.P.PP',
        '.F.FF',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHHH',
        'HHHHH',
        'SHHHS',
        'TTTTT',
        'UTTTU',
        'SPPP.',
        '.P.P.',
        '.F.F.',
      ],
  ],
  left: [
    [
        '.HHH.',
        'HHHHH',
        'HSHHH',
        'SESHH',
        '.SSH.',
        '.TTT.',
        '.TTU.',
        '.PST.',
        'P.PP.',
        'F.FF.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HSHHH',
        'SESHH',
        '.SSH.',
        '.TTT.',
        '.TTU.',
        '.PSS.',
        '.PP..',
        '.FF..',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HSHHH',
        'SESHH',
        '.SSH.',
        '.TTT.',
        '.TTU.',
        '.PST.',
        '.PP.P',
        '.FF.F',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HSHHH',
        'SESHH',
        '.SSH.',
        '.TTT.',
        '.TTU.',
        '.PSS.',
        '.PPP.',
        '.FFF.',
      ],
  ],
  right: [
    [
        '.HHH.',
        'HHHHH',
        'HHHSH',
        'HHSES',
        '.HSS.',
        '.TTT.',
        '.UTT.',
        '.TSP.',
        '.PP.P',
        '.FF.F',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHSH',
        'HHSES',
        '.HSS.',
        '.TTT.',
        '.UTT.',
        '.SSP.',
        '..PP.',
        '..FF.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHSH',
        'HHSES',
        '.HSS.',
        '.TTT.',
        '.UTT.',
        '.TSP.',
        'P.PP.',
        'F.FF.',
      ],
    [
        '.HHH.',
        'HHHHH',
        'HHHSH',
        'HHSES',
        '.HSS.',
        '.TTT.',
        '.UTT.',
        '.SSP.',
        '.PPP.',
        '.FFF.',
      ],
  ],
}

// Seated at the desk, reading: one frame. The monitor is the right-hand three columns.
export const MID_SEAT_READ: Grid = [
    '.HHH....',
    'HHHHH...',
    'HHHHH...',
    'HESEHNNN',
    'SSMSSNCN',
    'TTSTTNCN',
    'UTKTUNNN',
    'DDDDDDDD',
    'BBBBBBBB',
    'BB....BB',
  ]

// Seated, typing: two frames; a hand pixel moves along the desk top.
export const MID_SEAT_TYPE: readonly Grid[] = [
  [
      '.HHH....',
      'HHHHH...',
      'HHHHH...',
      'HESEHNNN',
      'SSMSSNCN',
      'TTSTTNCN',
      'UTKTUNNN',
      'DSDDDDDD',
      'BBBBBBBB',
      'BB....BB',
    ],
  [
      '.HHH....',
      'HHHHH...',
      'HHHHH...',
      'HESEHNNN',
      'SSMSSNCN',
      'TTSTTNCN',
      'UTKTUNNN',
      'DDDSDDDD',
      'BBBBBBBB',
      'BB....BB',
    ],
]
